defmodule Buzy.Llm.Clients.Gemini.Helpers do
  def map_role(:user), do: "user"
  def map_role(:system), do: "user"
  def map_role(:model), do: "model"

  def unmap_role("model"), do: :assistant
  def unmap_role("function"), do: :tool

  # https://ai.google.dev/api/generate-content#FinishReason

  # Default value. This value is unused.
  def map_finish_reason("FINISH_REASON_UNSPECIFIED"), do: :finish_reason_unspecified
  # Natural stop point of the model or provided stop sequence.
  def map_finish_reason("STOP"), do: :stop
  # The maximum number of tokens as specified in the request was reached.
  def map_finish_reason("MAX_TOKENS"), do: :max_tokens
  # The response candidate content was flagged for safety reasons.
  def map_finish_reason("SAFETY"), do: :safety
  # The response candidate content was flagged for recitation reasons.
  def map_finish_reason("RECITATION"), do: :recitation
  # The response candidate content was flagged for using an unsupported language.
  def map_finish_reason("LANGUAGE"), do: :language
  # Unknown reason.
  def map_finish_reason("OTHER"), do: :other
  # Token generation stopped because the content contains forbidden terms.
  def map_finish_reason("BLOCKLIST"), do: :blocklist
  # Token generation stopped for potentially containing prohibited content.
  def map_finish_reason("PROHIBITED_CONTENT"), do: :prohibited_content

  # Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
  def map_finish_reason("SPII"), do: :spii
  # The function call generated by the model is invalid.
  def map_finish_reason("MALFORMED_FUNCTION_CALL"), do: :malformed_function_call
  # Token generation stopped because generated images contain safety violations.
  def map_finish_reason("IMAGE_SAFETY"), do: :image_safety

  @doc """
  Decode a streamed response from an OpenAI-compatible server. Parses a string
  of received content into an Elixir map data structure using string keys.

  If a partial response was received, meaning the JSON text is split across
  multiple data frames, then the incomplete portion is returned as-is in the
  buffer. The function will be successively called, receiving the incomplete
  buffer data from a previous call, and assembling it to parse.
  """
  @spec decode_stream({String.t(), String.t()}) :: {%{String.t() => any()}}
  def decode_stream({raw_data, _buffer}, _done \\ []) do
    case raw_data do
      <<"[{\n  \"error\":", _rest::binary>> ->
        parse_chunk(raw_data)

      <<"[", chunk::binary>> ->
        parse_chunk(chunk)

      <<",", chunk::binary>> ->
        parse_chunk(chunk)

      <<"]">> ->
        parse_chunk("")

      "" ->
        parse_chunk("")

      chunk ->
        parse_chunk(chunk)
    end
  end

  defp parse_chunk(""), do: {nil, ""}

  defp parse_chunk(chunk) do
    case Jason.decode(chunk) do
      {:ok, parsed} ->
        {parsed, ""}

      {:error, _reason} ->
        {nil, chunk}
    end
  end
end
